<?php

namespace org\cim\proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class orgcimPracticeSessionProxy extends \org\cim\PracticeSession implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setUser($user)
    {
        $this->_load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->_load();
        return parent::getUser();
    }

    public function setMusicPiece($musicPiece)
    {
        $this->_load();
        return parent::setMusicPiece($musicPiece);
    }

    public function getMusicPiece()
    {
        $this->_load();
        return parent::getMusicPiece();
    }

    public function setInstrument($instrument)
    {
        $this->_load();
        return parent::setInstrument($instrument);
    }

    public function getInstrument()
    {
        $this->_load();
        return parent::getInstrument();
    }

    public function addSetting($setting)
    {
        $this->_load();
        return parent::addSetting($setting);
    }

    public function getSettings()
    {
        $this->_load();
        return parent::getSettings();
    }

    public function addPracticeRecording($practiceRecording)
    {
        $this->_load();
        return parent::addPracticeRecording($practiceRecording);
    }

    public function getPracticeRecordings()
    {
        $this->_load();
        return parent::getPracticeRecordings();
    }

    public function addAnnotation($annotation)
    {
        $this->_load();
        return parent::addAnnotation($annotation);
    }

    public function getAnnotations()
    {
        $this->_load();
        return parent::getAnnotations();
    }

    public function load()
    {
        $this->_load();
        return parent::load();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'createdDate', 'lastAccessDate', 'lifecycle', 'id', 'musicPiece', 'instrument', 'settings', 'practiceRecordings', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}