<?php

namespace org\cim\proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class orgcimMusicPieceProxy extends \org\cim\MusicPiece implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setConductorUser($user)
    {
        $this->_load();
        return parent::setConductorUser($user);
    }

    public function getConductorUser()
    {
        $this->_load();
        return parent::getConductorUser();
    }

    public function addScore($score)
    {
        $this->_load();
        return parent::addScore($score);
    }

    public function getScores()
    {
        $this->_load();
        return parent::getScores();
    }

    public function addGenre($genre)
    {
        $this->_load();
        return parent::addGenre($genre);
    }

    public function getGenres()
    {
        $this->_load();
        return parent::getGenres();
    }

    public function load()
    {
        $this->_load();
        return parent::load();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pieceName', 'composer', 'performingEnsemble', 'recordedDate', 'conductorName', 'description', 'thumbnailSet', 'conductorsViewStream', 'id', 'conductorUser', 'scores', 'genres');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}