<?php

namespace org\cim\proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class orgcimInstrumentProxy extends \org\cim\Instrument implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function setParentInstrument($message)
    {
        $this->_load();
        return parent::setParentInstrument($message);
    }

    public function getParentInstrument()
    {
        $this->_load();
        return parent::getParentInstrument();
    }

    public function addChildInstrument($instrument)
    {
        $this->_load();
        return parent::addChildInstrument($instrument);
    }

    public function getChildInstruments()
    {
        $this->_load();
        return parent::getChildInstruments();
    }

    public function load()
    {
        $this->_load();
        return parent::load();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('instrumentName', 'id', 'childInstruments', 'parentInstrument');
    }
}